name: Rust

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

env:
  CARGO_TERM_COLOR: always

jobs:
  ci:
    name: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - uses: actions/checkout@v4
      - name: Check formatting
        run: cargo fmt --check --verbose
      - name: Build
        run: cargo build --verbose
      - name: Check linting
        run: cargo clippy -- -D warnings
      - name: Run tests
        run: cargo test --verbose

